"""SVG file generation."""

import os
from .tracer import VectorPath


def generate_svg(
    paths: list[VectorPath],
    width: int,
    height: int,
    optimize: bool = False,
    stroke_width: float = 0.0,
) -> str:
    """Generate SVG XML string from vector paths."""
    lines = []
    lines.append('<?xml version="1.0" encoding="UTF-8"?>')
    lines.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="0 0 {width} {height}" '
        f'width="{width}" height="{height}">'
    )
    lines.append(f'  <title>vectormage output</title>')
    lines.append(f'  <desc>Generated by vectormage v0.1.0</desc>')

    for i, vp in enumerate(paths):
        r, g, b, a = vp.color
        fill_color = f"rgb({r},{g},{b})"
        opacity = a / 255.0 if a < 255 else 1.0

        fill_attr = f'fill="{fill_color}"'
        if opacity < 1.0:
            fill_attr += f' opacity="{opacity:.2f}"'

        if stroke_width > 0:
            lines.append(
                f'  <path d="{vp.path_data}" '
                f'{fill_attr} '
                f'stroke="{fill_color}" stroke-width="{stroke_width}"/>'
            )
        else:
            lines.append(f'  <path d="{vp.path_data}" {fill_attr}/>')

    lines.append('</svg>')
    return "\n".join(lines)


def write_svg(svg_content: str, output_path: str) -> str:
    """Write SVG content to file. Returns the output path."""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(svg_content)
    return output_path
